version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./common/rails/Dockerfile
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - ./web:/web
    links:
      - db
    extends:
      file: ./common/mysql/password.yml
      service: password
  db:
    build:
      context: .
      dockerfile: ./common/mysql/Dockerfile
    ports:
      - '3306:3306'
    extends:
      file: ./common/mysql/password.yml
      service: password
