AWSTemplateFormatVersion: 2010-09-09
Description: "Use check list information in Gamera ECS instance"

Parameters:

  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-northeast-1a
  ImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-9cd57ffd
  InstanceType:
    Type : String
    Default: t2.medium
    AllowedValues:
      - t2.small
      - t2.medium
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: gamera's instance key
    Default: gamera
  SecurityGroupId:
    Type: CommaDelimitedList
    Default: sg-0bd83903cddd53053
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-05f8294ff59f67724
    Description: AZ has used A zone 
  ECSCluster:
    Type: String
    Default: GameraCluster
  EC2Role:
    Type: String
    Default: gamera-ecs-role-EC2Role-JX29WY19XOHF

Resources:

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: false
            VolumeSize: 100
      InstanceInitiatedShutdownBehavior: stop
      Monitoring: true
      SourceDestCheck: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet: !Ref SecurityGroupId
          SubnetId: !Ref SubnetId
      IamInstanceProfile: !Ref EC2InstanceProfile
      Tags:
        - Key: Name
          Value: gamera-instance01
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref EC2Role