AWSTemplateFormatVersion: 2010-09-09
Description: "Use check list information in Gamera ECS service"

Parameters:

  Cluster:
    Type: String
    Default: GameraCluster
  ELBTarget:
    Type: String
    Default: arn:aws:elasticloadbalancing:ap-northeast-1:748552758785:targetgroup/GameraALBTargets/3964c0ba73661461
  TaskDefinition:
    Type: String
    Default: gamera-ecs-task-GameraWeb-1DVL1HPOXQBYZ:1
  ContainerName:
    Type: String
    Default: gameraweb
  ECSRole:
    Type: String
    Default: gamera-ecs-role-ECSServiceRole-1ADOR8AUMSP60
  
Resources:
  Rails:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      LaunchType: EC2
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: !Ref ContainerName
          ContainerPort: 3000
          TargetGroupArn: !Ref ELBTarget
      Role: !Ref ECSRole
      TaskDefinition: !Ref TaskDefinition