AWSTemplateFormatVersion: 2010-09-09
Description: "Use check list information in Gamera ECS ELB"

Parameters:

  InstanceA:
    Type: AWS::EC2::Instance::Id
    Default: i-0bed958849a076e10
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-0914afbbdd372687a
  SubnetIdA:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-05f8294ff59f67724
  SubnetIdC:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-080d8e8a519ce63c0
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-0bd83903cddd53053
  AlbOriginSSLCertificateId:
    Type: String
    Default: arn:aws:acm:ap-northeast-1:748552758785:certificate/e6a49c30-b018-4d07-929b-e0d165041eed

Resources:

  GameraFrontALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: gamera-front-alb
      Type: application
      Subnets:
        - !Ref SubnetIdA
        - !Ref SubnetIdC
      SecurityGroups: 
        - !Ref SecurityGroupId
  GameraALBListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref GameraALBTargets
          Type: forward
      LoadBalancerArn: !Ref GameraFrontALB
      Port: "443"
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref AlbOriginSSLCertificateId
      SslPolicy: "ELBSecurityPolicy-2016-08"
  GameraALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: GameraALBListener
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref GameraALBTargets
      Conditions:
      - Field: path-pattern
        Values: [/]
      ListenerArn: !Ref GameraALBListener
      Priority: 1
  GameraALBTargets:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    DependsOn: GameraFrontALB
    Properties:
      Name: GameraALBTargets
      Port: "80"
      Protocol: HTTP
      VpcId: !Ref VpcId
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 10
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      Targets:
        - Id: !Ref InstanceA
          Port: "80"