default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: db
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: gamera_dev
  
production:
  <<: *default
  database: gamera
  username: gamera
  password: gameragamera
  host: rds.prv.gamera.mediba-dev.tools
